name: Deploy Backend to Render
on:
  push:
    branches: [main]
    paths: ['server/**']
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: { node-version: '16' }
      - name: Install dependencies
        run: cd server && npm install
      - name: Test server locally
        run: cd server && npm start &
        env:
          PORT: 5000
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          response=$(curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{}' \
          -w "\nHTTP_STATUS:%{http_code}" \
          "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys")
          echo "Render API Response: $response"
          http_status=$(echo "$response" | grep "HTTP_STATUS" | cut -d':' -f2)
          if [ "$http_status" -ne 200 ] && [ "$http_status" -ne 201 ]; then
            echo "Deployment failed with HTTP status: $http_status"
            exit 1
          fi